<a href="https://colab.research.google.com/github/Panth23/Machine-Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)] # for loop to assign value from 1 to 1000

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)

0.0015383260000003673


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()
print(end_time-start_time)

0.0008850579999997166


Numpy array

In [ ]:
list_1 = [1,2,3,4,5]
print(list_1)
type(list_1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape #first --> no.of rows and second --> no.of coloumns

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy array

In [ ]:
#creating numpy arrays with zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating an array of ones
y = np.ones((3,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.99671011 0.99843158 0.91172289 0.48229663]
 [0.22609682 0.42128697 0.14536015 0.08752662]
 [0.90946975 0.28711961 0.71089597 0.96058992]]


In [ ]:
# random integer values array
b = np.random.randint(10,100,(3,5))
print(b)

[[87 79 22 57 34]
 [63 38 54 43 32]
 [58 40 36 90 49]]


In [ ]:
# an array of evenly spaced values ---> specifying the no.of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values ---> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [3]:
#convert a list to numpy array
list2 = [1,2,3,4]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

Analyzing a numpy array

In [7]:
c = np.random.randint(10,90,(5,5))
print(c)

[[37 33 83 73 19]
 [55 12 54 29 55]
 [33 33 72 89 13]
 [77 18 61 22 54]
 [55 36 72 87 43]]


In [8]:
print(c.shape)

(5, 5)


In [10]:
#no.of dimensions
print(c.ndim)

2


In [11]:
# number of elements in an array
print(c.size)

25


In [12]:
#checking the datatype in numpy array
print(c.dtype)

int64


Mathematical operations on a np array

In [13]:
# in case of a list if i try to add two list by '+' then it would not happen instead the lists would get concatinated
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [15]:
print(a)
print(b)

[[3 2 5]
 [0 4 9]
 [1 2 6]]
[[11 15 10]
 [13 13 15]
 [10 16 15]]


In [17]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 17 15]
 [13 17 24]
 [11 18 21]]
[[ -8 -13  -5]
 [-13  -9  -6]
 [ -9 -14  -9]]
[[ 33  30  50]
 [  0  52 135]
 [ 10  32  90]]
[[0.27272727 0.13333333 0.5       ]
 [0.         0.30769231 0.6       ]
 [0.1        0.125      0.4       ]]


In [18]:
print(np.add(a,b))

[[14 17 15]
 [13 17 24]
 [11 18 21]]


In [20]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ -8 -13  -5]
 [-13  -9  -6]
 [ -9 -14  -9]]
[[ 33  30  50]
 [  0  52 135]
 [ 10  32  90]]
[[0.27272727 0.13333333 0.5       ]
 [0.         0.30769231 0.6       ]
 [0.1        0.125      0.4       ]]


Array Manipulation

In [22]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 9 0]
 [2 4 6]]
(2, 3)


In [23]:
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[0 2]
 [9 4]
 [0 6]]
(3, 2)


In [24]:
trans2 = array.T
print(trans2)
print(trans.shape)

[[0 2]
 [9 4]
 [0 6]]
(3, 2)


In [25]:
#reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 4 6]
 [7 9 2]]
(2, 3)


In [26]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 4]
 [6 7]
 [9 2]]
(3, 2)
